dad_short_reads: "/mnt/beegfs/labs/DiGenomaLab/rfhap/latest_dami/latest_HG00_dataset/HG002/son/short/HG002_HiSeq30x_subsampled_R*.fastq.gz"
mom_short_reads: "/mnt/beegfs/labs/DiGenomaLab/rfhap/latest_dami/latest_HG00_dataset/HG002/son/short/HG002_HiSeq30x_subsampled_R*.fastq.gz"
child_short_reads: "/mnt/beegfs/labs/DiGenomaLab/rfhap/latest_dami/latest_HG00_dataset/HG002/son/short/HG002_HiSeq30x_subsampled_R*.fastq.gz"
child_long_reads: "/mnt/beegfs/labs/DiGenomaLab/rfhap/latest_dami/latest_HG00_dataset/HG002/son/short/HG002_HiSeq30x_subsampled_R*.fastq.gz"
hap_A_ids: "/mnt/beegfs/labs/DiGenomaLab/rfhap/analysis_bayesian/results_0.1/A.csv"
hap_B_ids: "/mnt/beegfs/labs/DiGenomaLab/rfhap/analysis_bayesian/results_0.1/B.csv"
