dad_short_reads_R1: "/mnt/beegfs/labs/DiGenomaLab/rfhap/Eval-RF-hap/data/dad_short_reads_R1.txt"
dad_short_reads_R2: "/mnt/beegfs/labs/DiGenomaLab/rfhap/Eval-RF-hap/data/dad_short_reads_R2.txt"

mom_short_reads_R1: "/mnt/beegfs/labs/DiGenomaLab/rfhap/Eval-RF-hap/data/mom_short_reads_R1.txt"
mom_short_reads_R2: "/mnt/beegfs/labs/DiGenomaLab/rfhap/Eval-RF-hap/data/mom_short_reads_R2.txt"

child_short_reads_R1: "/mnt/beegfs/labs/DiGenomaLab/rfhap/Eval-RF-hap/data/child_short_reads_R1.txt"
child_short_reads_R2: "/mnt/beegfs/labs/DiGenomaLab/rfhap/Eval-RF-hap/data/child_short_reads_R2.txt"

child_long_reads: "/mnt/beegfs/labs/DiGenomaLab/rfhap/Eval-RF-hap/data/child_long_reads.txt"

hap_mom_ids: "/mnt/beegfs/labs/DiGenomaLab/rfhap/analysis_bayesian/results_0.1/A.csv"
hap_dad_ids: "/mnt/beegfs/labs/DiGenomaLab/rfhap/analysis_bayesian/results_0.1/B.csv"
hap_unknown_ids: "/mnt/beegfs/labs/DiGenomaLab/rfhap/analysis_bayesian/results_0.1/U.csv"
